logging:
  level:
    root: INFO
    com.pritamprasad: TRACE
    org:
      springframework:
        security: ERROR
covid19india:
  url:
    latestLog: https://api.covid19india.org/updatelog/log.json
    datewiseSummary: https://api.covid19india.org/v4/min/data-YYYY-MM-DD.min.json
  fixedDelay: 86400000   #in millis
  timeTravelMinusDays: 2
  pastDataInNumberOfDays: 15
auth:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 300000
---
spring:
  profiles:
    - dev
  datasource:
    url: jdbc:postgresql://${COVID_DB_HOST}:5432/coviddb
    username: ${COVID_DB_USER}
    password: ${COVID_DB_PASS}
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 5
      idle-timeout: 300000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
---
spring:
  profiles:
    - local
  datasource:
    url: jdbc:h2:mem:coviddb
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 300000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

